### ISSUE TITLE
embed.FS broken on Windows

### ISSUE THREAD

**Issue by shemanaev** [vorlif/spreak#12]
#### Summary

Go uses forward slashes for `embed.FS` even on Windows builds and [loader](https://github.com/vorlif/spreak/blob/b7cb50739f4d4e65ac8f1a05d6cfa5cde07e7641/loader.go#L248) can't find files with names made with `filepath.Join`.

Relevant issues: golang/go#45230, golang/go#44305

#### Steps to reproduce

Move `locale/es.po` to `locale/es/helloworld.po` in [example](https://github.com/vorlif/spreak/tree/main/examples/features/embed).

#### Expected behavior

Load locales.

#### Observed behavior (that appears unintentional)

It doesn't load 😄.

**Comment by vorlif** [comment]
Hi @shemanaev,

Thanks for bringing up this point and for your research!

I'll have to have a look at how best to solve the problem while remaining compatible with the normal and embedded filesystem.

As a temporary fix, you could use a [custom revolver](https://github.com/vorlif/spreak/blob/main/examples/features/resolver/main.go) with `path.Join`.

```go
fsLoader, errFS := spreak.NewFilesystemLoader(
	spreak.WithResolver(&yourResolver{}),
	spreak.WithFs(yourFs),
)
```

**Comment by vorlif** [comment]
That took longer than it should have. Unfortunately, there is no way to determine if it is an embedded filesystem. But according to the [fs documentation](https://pkg.go.dev/io/fs#ValidPath), slashes should be used as path separators for fs.FS implementations anyway.

However, I have now created a new release, with which it should also work under Windows. Thanks for your report.

**Comment by shemanaev** [comment]
Everything works perfect now. Thank you! 👍
